### ISSUE TITLE
Error callback idea

### ISSUE THREAD

**Issue by lonelycode** [krolaw/xsd#1]
Did some research and it looks like callbacks are possible, and I think the reason the go code won't work is because you can't send a go function pointer into a CGo call without a custom wrapper, this fella talks about a [sample implementation here](http://cheesesun.blogspot.co.uk/2010/04/callbacks-in-cgo.html).

I don't understand enough about how libxml works (and my C is rusty at best), so I'm not sure if I can replicate it using `C.xmlSchemaGetValidErrors()`, but i think the trick is:
- Create a wrapper for `C.xmlSchemaGetValidErrors` and define it some C code (included with the package), call it `xmlSchemaGetValidErrorsWrapper`
- `xmlSchemaGetValidErrorsWrapper` does not need a callback parameter, instead, it calls `xmlSchemaGetValidErrors` directly, explicitly naming the pointer to the exported Golang function
- In the go code, call the wrapper instead of `xmlSchemaGetValidErrors`

I just can't figure out al the types for the wrapper function...

Just an idea, what do you think?

**Comment by krolaw** [comment]
Thanks for the link on how to do callbacks, it looks like a winner.  My C is awful, but I'll give it a shot when  I have some time up my sleeve.  Hopefully soon, not promising anything - but don't let my intentions stop you from having a go :-)

**Comment by krolaw** [comment]
This was a good idea to get around a problem with collecting errors.  But with the latest commit, I don't think it's really necessary.  Thanks for your efforts though :-)
